# .github/workflows/sync-upstream.yml

name: Sync Upstream CyberChef

on:
  # Schedule this workflow to run once a day at midnight UTC
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  
  # Allow manual triggering of the workflow from the GitHub UI
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Add upstream remote
        run: git remote add upstream https://github.com/gchq/CyberChef.git

      - name: Fetch upstream gh-pages branch
        run: git fetch upstream gh-pages

      - name: Force push upstream gh-pages to fork's gh-pages
        run: git push --force origin upstream/gh-pages:gh-pages

      - name: Fetch updated origin references
        run: git fetch origin

      - name: Checkout gh-pages for cleanup 
        run: git checkout -B gh-pages origin/gh-pages

      - name: Clean up old CyberChef zip files
        run: |
          LATEST_ZIP=$(ls -v CyberChef_v*.zip 2>/dev/null | tail -n 1)
          if [ -z "$LATEST_ZIP" ]; then
            echo "No CyberChef zip files found to clean up."
          else
            echo "Latest CyberChef zip file detected: $LATEST_ZIP"
            for FILE in CyberChef_v*.zip; do
              if [ "$FILE" != "$LATEST_ZIP" ]; then
                echo "Deleting old zip file: $FILE"
                rm "$FILE"
              fi
            done
            echo "Cleanup complete."
          fi
        working-directory: './' 

      - name: Commit cleanup changes and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated: Cleaned up old CyberChef zip files" || echo "No changes to commit."
          git push origin gh-pages
